# name of the software
name: Ideal Postcodes Location Service
# licence of the software
license: Apache 2.0
licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html

# This variable should be kept commented for local testing, it is uncommented by a script for production
#baseurl: /IdealPostcodes

# list of additional links on the right of the top menu
headerLinks:
#  - title: GitHub
#    url: https://github.com/mistic100/jekyll-bootstrap-doc

# list if additional links on the footer
footerLinks:
  - title: <i class="fa fa-github"></i>GitHub
    url: https://github.com/BricksandMortar/IdealPostcodes
  - title: Issues
    url: https://github.com/BricksandMortar/IdealPostcodes/issues?state=open

# header
header:
  color1: "#E64C29"
  color2: "#E64C29"

rockstore:
  url:

# google analytics
analytics:
  account:
  domain:

# github buttons
github:
  user: BricksandMortar
  repo: IdealPostcodes

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account: arranf


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile', vendor, script, Rakefile]

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
