#!/usr/bin/env bash
set -e # halt script on error

cd ..
git clone --depth=50 --branch=gh-pages https://github.com/BricksandMortar/plugin-doc-template.git
rm -rf plugin-doc-template/.git
cp -r -n plugin-doc-template/* $TRAVIS_REPO_SLUG/
cd $TRAVIS_REPO_SLUG
